name: "radio"

services:
    app:
        image: "radio:latest"
        restart: unless-stopped
        ports:
            - 127.0.0.1:8080:8080
        networks:
            - network

networks:
    network:
        driver: bridge
