name: "radio"

services:
    app:
        image: "radio:latest"
        restart: unless-stopped
        networks:
            - network

    proxy:
        image: "nginx:latest"
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on:
            - app
        networks:
            - network
        

networks:
    network:
        driver: bridge
